name: NASA Project CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa_db
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ["6.0"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: npm install
      - name: Build client app
        run: npm run build --prefix client
      - name: Run tests
        run: npm test
